/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as JoinRouteImport } from './routes/join'
import { Route as CreatePollRouteImport } from './routes/create-poll'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ManageAdminTokenRouteImport } from './routes/manage.$adminToken'
import { Route as PollPollIdUserIdRouteImport } from './routes/poll.$pollId.$userId'

const JoinRoute = JoinRouteImport.update({
  id: '/join',
  path: '/join',
  getParentRoute: () => rootRouteImport,
} as any)
const CreatePollRoute = CreatePollRouteImport.update({
  id: '/create-poll',
  path: '/create-poll',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ManageAdminTokenRoute = ManageAdminTokenRouteImport.update({
  id: '/manage/$adminToken',
  path: '/manage/$adminToken',
  getParentRoute: () => rootRouteImport,
} as any)
const PollPollIdUserIdRoute = PollPollIdUserIdRouteImport.update({
  id: '/poll/$pollId/$userId',
  path: '/poll/$pollId/$userId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/create-poll': typeof CreatePollRoute
  '/join': typeof JoinRoute
  '/manage/$adminToken': typeof ManageAdminTokenRoute
  '/poll/$pollId/$userId': typeof PollPollIdUserIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/create-poll': typeof CreatePollRoute
  '/join': typeof JoinRoute
  '/manage/$adminToken': typeof ManageAdminTokenRoute
  '/poll/$pollId/$userId': typeof PollPollIdUserIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/create-poll': typeof CreatePollRoute
  '/join': typeof JoinRoute
  '/manage/$adminToken': typeof ManageAdminTokenRoute
  '/poll/$pollId/$userId': typeof PollPollIdUserIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/create-poll'
    | '/join'
    | '/manage/$adminToken'
    | '/poll/$pollId/$userId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/create-poll'
    | '/join'
    | '/manage/$adminToken'
    | '/poll/$pollId/$userId'
  id:
    | '__root__'
    | '/'
    | '/create-poll'
    | '/join'
    | '/manage/$adminToken'
    | '/poll/$pollId/$userId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CreatePollRoute: typeof CreatePollRoute
  JoinRoute: typeof JoinRoute
  ManageAdminTokenRoute: typeof ManageAdminTokenRoute
  PollPollIdUserIdRoute: typeof PollPollIdUserIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/join': {
      id: '/join'
      path: '/join'
      fullPath: '/join'
      preLoaderRoute: typeof JoinRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/create-poll': {
      id: '/create-poll'
      path: '/create-poll'
      fullPath: '/create-poll'
      preLoaderRoute: typeof CreatePollRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/manage/$adminToken': {
      id: '/manage/$adminToken'
      path: '/manage/$adminToken'
      fullPath: '/manage/$adminToken'
      preLoaderRoute: typeof ManageAdminTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/poll/$pollId/$userId': {
      id: '/poll/$pollId/$userId'
      path: '/poll/$pollId/$userId'
      fullPath: '/poll/$pollId/$userId'
      preLoaderRoute: typeof PollPollIdUserIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CreatePollRoute: CreatePollRoute,
  JoinRoute: JoinRoute,
  ManageAdminTokenRoute: ManageAdminTokenRoute,
  PollPollIdUserIdRoute: PollPollIdUserIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
